#!/usr/bin/env python3
"""Generate and optionally execute a deterministic Blender scene build script."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path
from typing import Any


SUPPORTED_PRIMITIVES = {
    "box", "sphere", "ellipsoid", "cylinder", "cone", "capsule", "torus", "plane-card",
    "tube", "curve-sweep", "lathe", "extrude", "ground-blade", "instanced-cluster",
}


def load_spec(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("spec must be a JSON object")
    return payload


def validate_spec(spec: dict[str, Any]) -> None:
    components = spec.get("componentTree")
    if not isinstance(components, list) or not components:
        raise ValueError("spec.componentTree must be a non-empty array")
    ids: set[str] = set()
    for index, component in enumerate(components):
        if not isinstance(component, dict):
            raise ValueError(f"componentTree[{index}] must be an object")
        component_id = component.get("id")
        if not isinstance(component_id, str) or not component_id:
            raise ValueError(f"componentTree[{index}].id must be a non-empty string")
        if component_id in ids:
            raise ValueError(f"duplicate component id: {component_id}")
        ids.add(component_id)
        primitive = component.get("primitive", "box")
        if primitive not in SUPPORTED_PRIMITIVES:
            raise ValueError(f"unsupported Blender primitive {primitive!r} on component {component_id!r}")
    for component in components:
        parent = component.get("parent")
        if parent is not None and parent not in ids:
            raise ValueError(f"unknown parent {parent!r} on component {component['id']!r}")


def render_script(
    spec: dict[str, Any], blend_path: Path, render_path: Path | None = None,
    gltf_path: Path | None = None, fbx_path: Path | None = None,
) -> str:
    spec_json = json.dumps(spec, ensure_ascii=False, sort_keys=True)
    blend_json = json.dumps(str(blend_path))
    render_json = json.dumps(str(render_path) if render_path else "")
    gltf_json = json.dumps(str(gltf_path) if gltf_path else "")
    fbx_json = json.dumps(str(fbx_path) if fbx_path else "")
    return f'''# Generated by img2blender. Edit the spec, not this file.
import bpy
import json
import math

SPEC = json.loads({json.dumps(spec_json)})
BLEND_PATH = {blend_json}
RENDER_PATH = {render_json}
GLTF_PATH = {gltf_json}
FBX_PATH = {fbx_json}


def scalar(value, default):
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, dict):
        for key in ("value", "estimate", "mean"):
            if isinstance(value.get(key), (int, float)):
                return float(value[key])
    return default


def rgba(value):
    value = value if isinstance(value, str) else "#808080"
    value = value.lstrip("#")
    if len(value) == 3:
        value = "".join(ch * 2 for ch in value)
    try:
        return tuple(int(value[i:i + 2], 16) / 255 for i in (0, 2, 4)) + (1.0,)
    except (ValueError, IndexError):
        return (0.5, 0.5, 0.5, 1.0)


def add_primitive(component):
    kind = component.get("primitive", "box")
    descriptor = component.get("geometryDescriptor") or {{}}
    if kind == "box":
        bpy.ops.mesh.primitive_cube_add(size=1)
    elif kind in ("sphere", "ellipsoid"):
        bpy.ops.mesh.primitive_uv_sphere_add(segments=32, ring_count=16, radius=0.5)
    elif kind == "cylinder":
        bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.5, depth=1)
    elif kind == "cone":
        bpy.ops.mesh.primitive_cone_add(vertices=32, radius1=0.5, radius2=0, depth=1)
    elif kind == "capsule":
        # A real three-piece capsule, joined into one mesh (not a stretched sphere).
        parts = []
        bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.5, depth=0.5)
        parts.append(bpy.context.object)
        for z in (-0.25, 0.25):
            bpy.ops.mesh.primitive_uv_sphere_add(segments=32, ring_count=16, radius=0.5, location=(0, 0, z))
            parts.append(bpy.context.object)
        bpy.ops.object.select_all(action="DESELECT")
        for part in parts:
            part.select_set(True)
        bpy.context.view_layer.objects.active = parts[0]
        bpy.ops.object.join()
    elif kind == "torus":
        bpy.ops.mesh.primitive_torus_add(major_radius=0.38, minor_radius=0.12, major_segments=32, minor_segments=12)
    elif kind == "plane-card":
        bpy.ops.mesh.primitive_plane_add(size=1)
    elif kind in ("tube", "curve-sweep"):
        curve = bpy.data.curves.new("sweep", type="CURVE")
        curve.dimensions = "3D"
        curve.bevel_depth = 0.08
        curve.bevel_resolution = 3
        spline = curve.splines.new("POLY")
        spine = descriptor.get("spinePoints") or descriptor.get("points") or [(-0.5, 0, 0), (0, 0.15, 0), (0.5, 0, 0)]
        spline.points.add(max(0, len(spine) - 1))
        for point, value in zip(spline.points, spine):
            value = list(value)[:3]
            value += [0] * (3 - len(value))
            value.append(1)
            point.co = value
        obj = bpy.data.objects.new("sweep", curve)
        bpy.context.collection.objects.link(obj)
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.convert(target="MESH")
    elif kind in ("extrude", "ground-blade"):
        mesh = bpy.data.meshes.new("extrude")
        profile = descriptor.get("profile2D") or {{}}
        points = profile.get("points") or [(-0.5, -0.5), (0.5, -0.5), (0.5, 0.5), (-0.5, 0.5)]
        depth = float(profile.get("depth", 0.1))
        count = len(points)
        vertices = [(float(p[0]), float(p[1]), z) for z in (-depth / 2, depth / 2) for p in points]
        faces = [tuple(range(count)), tuple(range(count, count * 2))[::-1]]
        for i in range(count):
            n = (i + 1) % count
            faces.append((i, n, count + n, count + i))
        mesh.from_pydata(vertices, [], faces)
        obj = bpy.data.objects.new("extrude", mesh)
        bpy.context.collection.objects.link(obj)
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
    elif kind == "lathe":
        # Default vase-like rotational profile. Component geometry data can refine this later.
        profile_data = descriptor.get("profile2D") or {{}}
        profile = profile_data.get("points") or [(0.22, -0.5), (0.35, -0.35), (0.3, 0.2), (0.18, 0.5)]
        segments = 32
        vertices = [(radius * math.cos(2 * math.pi * s / segments), radius * math.sin(2 * math.pi * s / segments), z)
                    for radius, z in profile for s in range(segments)]
        faces = []
        for ring in range(len(profile) - 1):
            for s in range(segments):
                n = (s + 1) % segments
                a, b = ring * segments + s, ring * segments + n
                c, d = (ring + 1) * segments + n, (ring + 1) * segments + s
                faces.append((a, b, c, d))
        mesh = bpy.data.meshes.new("lathe")
        mesh.from_pydata(vertices, [], faces)
        obj = bpy.data.objects.new("lathe", mesh)
        bpy.context.collection.objects.link(obj)
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
    elif kind == "instanced-cluster":
        bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=2, radius=0.5)
    else:
        raise ValueError(f"unsupported primitive: {{kind}}")
    return bpy.context.object


bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete(use_global=False)

materials = {{}}
for item in SPEC.get("materials", []):
    if not isinstance(item, dict) or not item.get("id"):
        continue
    material = bpy.data.materials.new(name=str(item.get("name") or item["id"]))
    material.use_nodes = True
    bsdf = material.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        bsdf.inputs["Base Color"].default_value = rgba(item.get("baseColor") or item.get("color"))
        bsdf.inputs["Roughness"].default_value = scalar(item.get("roughness"), 0.5)
        bsdf.inputs["Metallic"].default_value = scalar(item.get("metalness"), 0.0)
        if "Alpha" in bsdf.inputs:
            bsdf.inputs["Alpha"].default_value = scalar(item.get("opacity"), 1.0)
        transmission = scalar(item.get("transmission"), 0.0)
        transmission_input = bsdf.inputs.get("Transmission Weight") or bsdf.inputs.get("Transmission")
        if transmission_input:
            transmission_input.default_value = transmission
    materials[str(item["id"])] = material

objects = {{}}
for component in SPEC["componentTree"]:
    obj = add_primitive(component)
    obj.name = str(component["id"])
    transform = component.get("transform") or {{}}
    position = transform.get("position", [0, 0, 0])
    rotation = transform.get("rotation", [0, 0, 0])
    scale = transform.get("scale")
    if not isinstance(scale, list) or len(scale) != 3:
        dims = component.get("dimensions") or {{}}
        scale = [dims.get("width", 1), dims.get("height", 1), dims.get("depth", 1)]
    obj.location = tuple(float(v) for v in position)
    obj.rotation_euler = tuple(float(v) for v in rotation)
    obj.scale = tuple(float(v) for v in scale)
    material = materials.get(str(component.get("material", "")))
    if material and hasattr(obj.data, "materials"):
        obj.data.materials.append(material)
    objects[str(component["id"])] = obj

for component in SPEC["componentTree"]:
    parent_id = component.get("parent")
    if parent_id is not None:
        objects[str(component["id"])].parent = objects[str(parent_id)]

scene = bpy.context.scene
backend = SPEC.get("backend") or {{}}
scene.unit_settings.system = backend.get("unitSystem", "METRIC")
scene.render.engine = backend.get("renderEngine", "BLENDER_EEVEE_NEXT")
scene.render.resolution_x = int((SPEC.get("renderSettings") or {{}}).get("width", 1024))
scene.render.resolution_y = int((SPEC.get("renderSettings") or {{}}).get("height", 1024))
scene.render.resolution_percentage = 100
scene.render.image_settings.file_format = "PNG"

# A deterministic review camera; referenceCamera values override the safe default.
camera_data = bpy.data.cameras.new("ReviewCamera")
camera = bpy.data.objects.new("ReviewCamera", camera_data)
bpy.context.collection.objects.link(camera)
camera_spec = SPEC.get("referenceCamera") or {{}}
camera.location = tuple(camera_spec.get("position", [0, -4, 1.5]))
camera.rotation_euler = tuple(camera_spec.get("rotation", [math.radians(72), 0, 0]))
if camera_spec.get("projection") == "orthographic" or camera_spec.get("type") == "orthographic":
    camera_data.type = "ORTHO"
    camera_data.ortho_scale = float(camera_spec.get("orthoScale", 4.0))
else:
    camera_data.lens = float(camera_spec.get("focalLength", 50.0))
scene.camera = camera

world = scene.world or bpy.data.worlds.new("World")
scene.world = world
world.use_nodes = True
world.node_tree.nodes["Background"].inputs["Color"].default_value = (0.035, 0.035, 0.035, 1)
world.node_tree.nodes["Background"].inputs["Strength"].default_value = 0.35
for name, location, energy, size in [
    ("Key", (-3, -4, 5), 1000, 4.0),
    ("Fill", (4, -2, 2), 500, 3.0),
    ("Rim", (0, 3, 4), 750, 2.0),
]:
    light_data = bpy.data.lights.new(name, type="AREA")
    light_data.energy = energy
    light_data.shape = "DISK"
    light_data.size = size
    light = bpy.data.objects.new(name, light_data)
    light.location = location
    bpy.context.collection.objects.link(light)

scene["img2blender_schema"] = str(SPEC.get("schemaVersion", "unknown"))
bpy.ops.wm.save_as_mainfile(filepath=BLEND_PATH)
if RENDER_PATH:
    scene.render.filepath = RENDER_PATH
    bpy.ops.render.render(write_still=True)
if GLTF_PATH:
    bpy.ops.export_scene.gltf(filepath=GLTF_PATH, export_format="GLB")
if FBX_PATH:
    bpy.ops.export_scene.fbx(filepath=FBX_PATH, use_selection=False)
'''


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a Blender Python scene from an ObjectSculptSpec")
    parser.add_argument("spec", type=Path)
    parser.add_argument("--out", type=Path, required=True, help="generated Blender Python script")
    parser.add_argument("--blend", type=Path, required=True, help=".blend output written by the generated script")
    parser.add_argument("--render", type=Path, help="optional PNG review render written by Blender")
    parser.add_argument("--export-gltf", type=Path, help="optional binary glTF export written by Blender")
    parser.add_argument("--export-fbx", type=Path, help="optional FBX export written by Blender")
    parser.add_argument("--run", action="store_true", help="execute Blender in background mode after generation")
    args = parser.parse_args(argv)
    spec = load_spec(args.spec)
    validate_spec(spec)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.blend.parent.mkdir(parents=True, exist_ok=True)
    for optional_output in (args.render, args.export_gltf, args.export_fbx):
        if optional_output:
            optional_output.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_script(
        spec, args.blend.resolve(), args.render.resolve() if args.render else None,
        args.export_gltf.resolve() if args.export_gltf else None,
        args.export_fbx.resolve() if args.export_fbx else None,
    ), encoding="utf-8")
    print(f"BACKEND blender script={args.out} blend={args.blend} render={args.render or '-'}")
    if args.run:
        blender = shutil.which("blender")
        if not blender:
            raise RuntimeError("Blender executable not found; install Blender or omit --run")
        subprocess.run([blender, "--background", "--python", str(args.out.resolve())], check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
